package com.ampvita.clickopedia;

import android.app.Application;

import com.firebase.client.Firebase;

public class ClickopediaApplication extends Application {

    public static String[] top5000;
    public static Firebase myFirebaseRef;

    @Override
    public void onCreate() {
        super.onCreate();
        Firebase.setAndroidContext(this);

        myFirebaseRef = new Firebase("https://torid-heat-2250.firebaseio.com/");

        top5000 = new String[]{"Wiki",
                "Facebook",
                "YouTube",
                "Searching",
                "United States",
                "Lists of deaths by year",
                "Web search engine",
                "Google",
                "Wikipedia",
                "Favicon",
                "Barack Obama",
                "The Beatles",
                "Sex",
                "World War II",
                "Michael Jackson",
                "Lady Gaga",
                "United Kingdom",
                "Eminem",
                "Justin Bieber",
                "Pornography",
                "India",
                "Lil Wayne",
                "Adolf Hitler",
                "How I Met Your Mother",
                "The Big Bang Theory",
                "Glee (TV series)",
                "China",
                "World War I",
                "Miley Cyrus",
                "Canada",
                "Steve Jobs",
                "Kim Kardashian",
                "Australia",
                "Game of Thrones",
                "Selena Gomez",
                "Rihanna",
                "Sexual intercourse",
                "Sex position",
                "Internet Movie Database",
                "Harry Potter",
                "Japan",
                "Initial",
                "New York City",
                "Human penis size",
                "Germany",
                "September 11 attacks",
                "Abraham Lincoln",
                "Elizabeth II",
                "Taylor Swift",
                "France",
                "Nicki Minaj",
                "Doctor Who",
                "Masturbation",
                "House (TV series)",
                "Tupac Shakur",
                "Johnny Depp",
                "Vagina",
                "Martin Luther King",
                "Breaking Bad",
                "Katy Perry",
                "William Shakespeare",
                "Lost (TV series)",
                "Hypertext Transfer Protocol",
                "Naruto",
                "List of Presidents of the United States",
                "Russia",
                "RMS Titanic",
                "Dexter (TV series)",
                "Illuminati",
                "Kanye West",
                "Mark Zuckerberg",
                "List of How I Met Your Mother episodes",
                "Jay-Z",
                "Albert Einstein",
                "The Walking Dead (TV series)",
                "Drake (rapper)",
                "Mahatma Gandhi",
                "Angelina Jolie",
                "Global warming",
                "Family Guy",
                "1",
                "List of Naruto: Shippuden episodes",
                "Halloween",
                "Britney Spears",
                "Cristiano Ronaldo",
                "Gossip Girl",
                "The Avengers (2012 film)",
                "One Direction",
                "Adele",
                "Mila Kunis",
                "John F. Kennedy",
                "London",
                "2012 phenomenon",
                "Dwayne Johnson",
                "Batman",
                "Wonders of the World",
                "Penis",
                "True Blood",
                "The Dark Knight (film)",
                "Megan Fox",
                "Myspace",
                "Will Smith",
                "Henry VIII of England",
                "England",
                "Michael Jordan",
                "Avatar (2009 film)",
                "Vietnam War",
                "Lionel Messi",
                "Asperger syndrome",
                "Outlook.com",
                "The Dark Knight Rises",
                "List of The Big Bang Theory episodes",
                "Grey's Anatomy",
                "English language",
                "Anal sex",
                "Brazil",
                "The Vampire Diaries",
                "List of Glee episodes",
                "Leonardo da Vinci",
                "Nelson Mandela",
                "The Hunger Games",
                "Android (operating system)",
                "Italy",
                "Manchester United F.C.",
                "Spain",
                "Israel",
                "Demi Lovato",
                "Bill Gates",
                "List of House episodes",
                "Marilyn Monroe",
                "List of Doctor Who serials",
                "List of HTTP status codes",
                "List of Family Guy episodes",
                "Bruce Lee",
                "Two and a Half Men",
                "Arnold Schwarzenegger",
                "Philippines",
                "American Civil War",
                "PlayStation 3",
                "50 Cent",
                "Heroes (TV series)",
                "The Office (U.S. TV series)",
                "Fifty Shades of Grey",
                "Dr. Dre",
                "Madonna (entertainer)",
                "Star Wars",
                "Netherlands",
                "George W. Bush",
                "Osama bin Laden",
                "The Undertaker",
                "Kristen Stewart",
                "John Lennon",
                "Singapore",
                "Tom Cruise",
                "John Cena",
                "Bob Marley",
                "List of pornographic actresses by decade",
                "Elvis Presley",
                "Leonardo DiCaprio",
                "Heath Ledger",
                "Twitter",
                "Jesus",
                "Celebrity sex tape",
                "The Simpsons",
                "EBay",
                "Internet",
                "New Zealand",
                "Love",
                "Brad Pitt",
                "List of Naruto characters",
                "Mexico",
                "Cat",
                "Stephen Hawking",
                "Yahoo!",
                "European Union",
                "Seven deadly sins",
                "Mariah Carey",
                "America's Next Top Model",
                "Jersey Shore (TV series)",
                "Google Search",
                "South Park",
                "Charlie Sheen",
                "Dog",
                "Jennifer Lopez",
                "Napoleon",
                "Freemasonry",
                "Europe",
                "Bipolar disorder",
                "South Africa",
                "Friends",
                "List of Top Gear episodes",
                "IPhone",
                "Sons of Anarchy",
                "Chernobyl disaster",
                "Standard deviation",
                "Cannabis (drug)",
                "Apple Inc.",
                "WWE",
                "List of South Park episodes",
                "Turkey",
                "Metallica",
                "Bleach (manga)",
                "Sarah Palin",
                "G-force",
                "Los Angeles",
                "The Holocaust",
                "The Notorious B.I.G.",
                "Amy Winehouse",
                "Pornographic film actor",
                "Inception",
                "Cloud computing",
                "Linkin Park",
                "Microsoft",
                "Orgasm",
                "Supernatural (disambiguation)",
                "Jennifer Aniston",
                "Egypt",
                "Scarlett Johansson",
                "James Bond",
                "Snoop Dogg",
                "Valentine's Day",
                "Pakistan",
                "Transformers: Revenge of the Fallen",
                "Ronald Reagan",
                "Elizabeth I of England",
                "Franklin D. Roosevelt",
                "Charles Manson",
                "LeBron James",
                "Justin Timberlake",
                "RSS",
                "Kobe Bryant",
                "Switzerland",
                "NCIS (TV series)",
                "Natalie Portman",
                "Kesha",
                "List of Twilight characters",
                "Pink Floyd",
                "User Datagram Protocol",
                "Che Guevara",
                "Scrubs (TV series)",
                "Freddie Mercury",
                "Emma Watson",
                "George Washington",
                "Cascading Style Sheets",
                "Harry Potter (film series)",
                "Anne Hathaway",
                "Soviet Union",
                "Mark Wahlberg",
                "Hong Kong",
                "California",
                "Muhammad Ali",
                "North Korea",
                "A Song of Ice and Fire",
                "Iran",
                "List of emoticons",
                "Xbox 360",
                "Robert Pattinson",
                "Breast",
                "Dubai",
                "Islam",
                "Chris Brown",
                "Earth",
                "Gross domestic product",
                "Christmas",
                "Mad Men",
                "List of Bleach episodes",
                "FC Barcelona",
                "Titanic (1997 film)",
                "Lindsay Lohan",
                "Sweden",
                "Joseph Stalin",
                "Buddhism",
                "Olympic Games",
                "Bruno Mars",
                "Arsenal F.C.",
                "Sasha Grey",
                "2 Girls 1 Cup",
                ".xxx",
                "Cat anatomy",
                "Real Madrid C.F.",
                "Queen Victoria",
                "Isaac Newton",
                "Oral sex",
                "Whitney Houston",
                "Assassin's Creed",
                "Desperate Housewives",
                "American Idol",
                "2012 Summer Olympics",
                "Chelsea F.C.",
                "Hawaii",
                "Christian Bale",
                "Schizophrenia",
                "Nudity",
                "Ireland",
                "Hannah Montana",
                "Scientology",
                "Burj Khalifa",
                "List of Greek mythological figures",
                "New York",
                "Bill Clinton",
                "Zooey Deschanel",
                "Taiwan",
                "Robert Downey",
                "Fellatio",
                "Avatar: The Last Airbender",
                "President of the United States",
                "Nikola Tesla",
                "Gmail",
                "Vanessa Hudgens",
                "Twilight (series)",
                "Christina Aguilera",
                "Female ejaculation",
                "List of WWE personnel",
                "Alive",
                "List of Star Wars characters",
                "Spider-Man",
                "International Standard Book Number",
                "Diana",
                "Indonesia",
                "Shakira",
                "Red Hot Chili Peppers",
                "Washington",
                "Channing Tatum",
                "Poland",
                "T.I.",
                "Led Zeppelin",
                "Emoticon",
                "Periodic table",
                "Paris",
                "Bones (TV series)",
                "Jackie Chan",
                "Atomic bombings of Hiroshima and Nagasaki",
                "Jennifer Lawrence",
                "United Nations",
                "Pablo Picasso",
                "Christopher Columbus",
                "Transformers: Dark of the Moon",
                "Iron Man",
                "Clint Eastwood",
                "ICarly",
                "2010 FIFA World Cup",
                "Kurt Cobain",
                "2012",
                "Association football",
                "Cold War",
                "Computer",
                "Margaret Thatcher",
                "Skins (UK TV series)",
                "Neil Patrick Harris",
                "Windows 7",
                "Avril Lavigne",
                "Great Depression",
                "Grand Theft Auto IV",
                "List of A Song of Ice and Fire characters",
                "Catherine",
                "Greece",
                "Premier League",
                "Chicago",
                "Paper size",
                "Sylvester Stallone",
                "Jimi Hendrix",
                "Ryan Reynolds",
                "Ku Klux Klan",
                "Pokémon",
                "Entourage (TV series)",
                "Tuberculosis",
                "Triple H",
                "HIV/AIDS",
                "Criminal Minds",
                "Liverpool F.C.",
                "Clitoris",
                "Alexander the Great",
                "USB",
                "Mitt Romney",
                "Pink (singer)",
                "DNA",
                "David Bowie",
                "Argentina",
                "Macaulay Culkin",
                "Jim Carrey",
                "Fringe (TV series)",
                "Ashton Kutcher",
                "Norway",
                "AC/DC",
                "Taylor Lautner",
                "Deadpool",
                "The Lord of the Rings",
                "Africa",
                "Jonas Brothers",
                "Modern Family",
                "World Wide Web",
                "Pi",
                "Roger Federer",
                "Smallville",
                "Al Capone",
                "Hydrogen",
                "Greek alphabet",
                "Emma Stone",
                "Scotland",
                "Kaley Cuoco",
                "Downton Abbey",
                "Solar System",
                "Dragon Ball",
                "Malaysia",
                "The Black Eyed Peas",
                "Adam Sandler",
                "Pretty Little Liars (TV series)",
                "Saint Patrick's Day",
                "BDSM",
                "Human",
                "Bob Dylan",
                "Richard Nixon",
                "Brock Lesnar",
                "The Great Gatsby",
                "IPv6",
                "Vulva",
                "List of dog breeds",
                "Nicolas Cage",
                "Julius Caesar",
                "Chuck Norris",
                "Jessica Alba",
                "Puerto Rico",
                "Mike Tyson",
                "Vin Diesel",
                "Winston Churchill",
                "List of The Simpsons episodes",
                "List of highest-grossing films",
                "Zac Efron",
                "Prince (musician)",
                "South Korea",
                "Salman Khan",
                "Ludwig van Beethoven",
                "Muammar Gaddafi",
                "Tom Hanks",
                "One Tree Hill (TV series)",
                "Muhammad",
                "Burma",
                "David Beckham",
                "Denmark",
                "Ten Commandments",
                "Brittany Murphy",
                "Star Trek",
                "Vietnam",
                "Thanksgiving",
                "Sun",
                "The Rolling Stones",
                "MDMA",
                "Thomas Jefferson",
                "Lion",
                "Thailand",
                "Cocaine",
                "Diabetes mellitus",
                "Attack on Pearl Harbor",
                "Sandra Bullock",
                "Sherlock Holmes",
                "Johnny Cash",
                "Wolfgang Amadeus Mozart",
                "Script kiddie",
                "Queen (band)",
                "Warren Buffett",
                "That '70s Show",
                "C (programming language)",
                "Elizabeth Taylor",
                "Manny Pacquiao",
                "United Arab Emirates",
                "Paul McCartney",
                "United States Constitution",
                "Saudi Arabia",
                "Benjamin Franklin",
                "Harry Potter and the Deathly Hallows",
                "Wiz Khalifa",
                "Digimon",
                "Geographic coordinate system",
                "Coldplay",
                "Nicole Scherzinger",
                "Prince William",
                "Ernest Hemingway",
                "Hard disk drive",
                "Daylight saving time",
                "Star Trek (film)",
                "Sunny Leone",
                "UEFA Champions League",
                "Superman",
                "Manhattan",
                "Green Day",
                "Edgar Allan Poe",
                "Daft Punk",
                "Autism",
                "IPad",
                "Pneumonia",
                "RAID",
                "Methamphetamine",
                "Wi-Fi",
                "Ejaculation",
                "Zodiac",
                "Maslow's hierarchy of needs",
                "Jason Statham",
                "Joker (comics)",
                "Guns N' Roses",
                "Gangnam Style",
                "Sherlock (TV series)",
                "Theodore Roosevelt",
                "Crohn's disease",
                "Bruce Willis",
                "Multiple sclerosis",
                "Animal",
                "Bulgaria",
                "Hilary Duff",
                "Futurama",
                "Lockheed Martin F-35 Lightning II",
                "Korean War",
                "Thomas Edison",
                "Marilyn Manson",
                "James Franco",
                "Matt Damon",
                "Swine influenza",
                "Quentin Tarantino",
                "Afghanistan",
                "Taj Mahal",
                "San Francisco",
                "Slipknot (band)",
                "John McCain",
                "Intel Core",
                "Fuck",
                "Once Upon a Time (TV series)",
                "Prison Break",
                "Audrey Hepburn",
                "Rick Ross",
                "Ryan Gosling",
                "List of countries by GDP (nominal)",
                "Liam Neeson",
                "Amazon.com",
                "Akon",
                "Call of Duty",
                "Moon",
                "Tiger",
                "Andy Warhol",
                "The Game (rapper)",
                "Socialism",
                "Malcolm X",
                "YouPorn",
                "Jenna Jameson",
                "Salvador Dalí",
                "Mount Everest",
                "List of United States cities by population",
                "Iceland",
                "AK-47",
                "Prometheus (disambiguation)",
                "Usher (entertainer)",
                "Nuclear weapon",
                "Nazi Germany",
                "Hentai",
                "24 (TV series)",
                "World Trade Center",
                "One Piece",
                "Olivia Wilde",
                "Galileo Galilei",
                "Aishwarya Rai Bachchan",
                "Water",
                "Belgium",
                "Secure Digital",
                "Charles Darwin",
                "Sigmund Freud",
                "Hurricane Katrina",
                "Patrick Swayze",
                "Shaquille O'Neal",
                "Tramadol",
                "Twilight (2008 film)",
                "X-Men: First Class",
                "Bermuda Triangle",
                "X-Men",
                "Industrial Revolution",
                "Basketball",
                "George VI",
                "List of Game of Thrones episodes",
                "George Clooney",
                "Psychology",
                "Girls' Generation",
                "Assassination of John F. Kennedy",
                "Mars",
                "Joseph Gordon-Levitt",
                "Resident Evil",
                "Haiti",
                "Vincent van Gogh",
                "Grand Theft Auto (series)",
                "Agnosticism",
                "Walt Disney",
                "List of Super Bowl champions",
                "Seth MacFarlane",
                "United States Declaration of Independence",
                "Nirvana (band)",
                "Go (game)",
                "Charlie Chaplin",
                "Tiger Woods",
                "Big Bang",
                "Russell Brand",
                "Romania",
                "The Wire",
                "Kama Sutra",
                "Anonymous (group)",
                "Chinese New Year",
                "Katrina Kaif",
                "Texas",
                "Blood type",
                "FIFA World Cup",
                "Shia LaBeouf",
                "90210 (TV series)",
                "Columbine High School massacre",
                "Bed bug",
                "Michael Phelps",
                "Frank Sinatra",
                "Easter",
                "Oprah Winfrey",
                "Communism",
                "WikiLeaks",
                "Avenged Sevenfold",
                "Database",
                "SpongeBob SquarePants",
                "Operating system",
                "Tom Hardy",
                "Avengers (comics)",
                "HIV",
                "Skrillex",
                "HDMI",
                "Mobile phone",
                "French Revolution",
                "Chuck (TV series)",
                "Playboy",
                "Skyfall",
                "Great Wall of China",
                "Blog",
                "Captain America",
                "Pitbull (rapper)",
                "Yahoo! Mail",
                "Lockheed Martin F-22 Raptor",
                "Alice's Adventures in Wonderland",
                "List of Dragon Ball characters",
                "Muse (band)",
                "World population",
                "Floyd Mayweather",
                "Roman Empire",
                "Firefly (TV series)",
                "Narcissism",
                "Wizards of Waverly Place",
                "Catholic Church",
                "Kid Cudi",
                "Area 51",
                "Paris Hilton",
                "Fullmetal Alchemist",
                "Robert De Niro",
                "Circumcision",
                "Morgan Freeman",
                "XXX",
                "Mother's Day",
                "Gray wolf",
                "2010 in film",
                "Six Sigma",
                "Human body",
                "Watch",
                "Fascism",
                "Semi-acoustic guitar",
                "Nigeria",
                "Jean-Claude Van Damme",
                "Paranormal Activity",
                "Sacha Baron Cohen",
                "Proxy server",
                "Keanu Reeves",
                "Philosophy",
                "Sri Lanka",
                "Morocco",
                "Denial-of-service attack",
                "Blink-182",
                "Rome",
                "Black Death",
                "Karl Marx",
                "Daniel Radcliffe",
                "Weeds (TV series)",
                "Linux",
                "Arrested Development (TV series)",
                "Republican Party (United States)",
                "Finland",
                "Blake Lively",
                "Inglourious Basterds",
                "Fergie (singer)",
                "A Game of Thrones",
                "Demi Moore",
                "Hayden Panettiere",
                "IPod",
                "IPod Touch",
                "Gautama Buddha",
                "X-Men Origins: Wolverine",
                "Hemorrhoid",
                "United States presidential election",
                "Blu-ray Disc",
                "A",
                "LMFAO",
                "Hulk Hogan",
                "2011 in film",
                "Minecraft",
                "Kings of Leon",
                "Null",
                "List of Digimon Adventure characters",
                "Ottoman Empire",
                "List of social networking websites",
                "Volcano",
                "Ozzy Osbourne",
                "Iron Man 2",
                "Cuba",
                "Mona Lisa",
                "World of Warcraft",
                "Herpes simplex",
                "Earthquake",
                "NATO phonetic alphabet",
                "Coca-Cola",
                "Blood pressure",
                "Sean Combs",
                "Alicia Keys",
                "Anime",
                "CSI: Crime Scene Investigation",
                "Rafael Nadal",
                "Vampire",
                "Vitamin D",
                "Call of Duty: Modern Warfare 2",
                "Gout",
                "Cloverfield",
                "A.C. Milan",
                "Gold",
                "Microsoft Windows",
                "Paul Walker",
                "The Pussycat Dolls",
                "Rachel McAdams",
                "Mumbai",
                "Transformers (film)",
                "Daniel Craig",
                "Ethanol",
                "Bradley Cooper",
                "Coffee",
                "Eye color",
                "Romeo and Juliet",
                "Neil Armstrong",
                "Pirates of the Caribbean (film series)",
                "Watchmen",
                "Iron Man (disambiguation)",
                "Jim Parsons",
                "Paramore",
                "Jamaica",
                "George H. W. Bush",
                "NATO",
                "The Girl with the Dragon Tattoo",
                "Fourteenth Amendment to the United States Constitution",
                "Lysergic acid diethylamide",
                "Dakota Fanning",
                "Lana Del Rey",
                "Normal distribution",
                "Walking Dead",
                "Michael Oher",
                "Auschwitz concentration camp",
                "Ivy League",
                "Alaska",
                "Steven Spielberg",
                "List of Bollywood films of 2013",
                "Kate Winslet",
                "Manchester City F.C.",
                "Jack the Ripper",
                "Al Pacino",
                "XXX (film)",
                "Meme",
                "Parkinson's disease",
                "The Hunger Games (film)",
                "United States Marine Corps",
                "Hugh Jackman",
                "Aristotle",
                "Ted Bundy",
                "Airbus A380",
                "United States Bill of Rights",
                "McDonald's",
                "List of Mortal Kombat characters",
                "Sachin Tendulkar",
                "Native Americans in the United States",
                "Wedding",
                "National Football League",
                "Wii",
                "List of unusual deaths",
                "Statue of Liberty",
                "Keira Knightley",
                "Bangladesh",
                "The Godfather",
                "Nas",
                "Chris Hemsworth",
                "Dubstep",
                "Boardwalk Empire",
                "Java",
                "Saturday Night Live",
                "Zeus",
                "Emo",
                "Existentialism",
                "Man of Steel (film)",
                "Obsessive–compulsive disorder",
                "Craigslist",
                "2008 Summer Olympics",
                "Tsunami",
                "Ukraine",
                "Capital punishment",
                "American Revolutionary War",
                "Oxycodone",
                "Friedrich Nietzsche",
                "Greenhouse gas",
                "Florida",
                "Iraq War",
                "Absinthe",
                "Globalization",
                "Genghis Khan",
                "Eiffel Tower",
                "Castle (TV series)",
                "Caffeine",
                "Gwyneth Paltrow",
                "Search engine optimization",
                "Buffy the Vampire Slayer",
                "Charles Dickens",
                "Ashley Tisdale",
                "Qatar",
                "Cheryl Cole",
                "List of The Vampire Diaries episodes",
                "Boston",
                "Semicolon",
                "Community (TV series)",
                "Thor (film)",
                "Cancer",
                "Backslash",
                "Serial ATA",
                "Charles",
                "Kiss (band)",
                "Philadelphia",
                "The Fast and the Furious",
                "List of Wizards of Waverly Place episodes",
                "2009 in film",
                "Usain Bolt",
                "X-Men (film series)",
                "Cameron Diaz",
                "It's Always Sunny in Philadelphia",
                "Amanda Bynes",
                "Boat",
                "Miranda Cosgrove",
                "2012 in film",
                "Spartacus",
                "Christianity",
                "Colombia",
                "Donald Trump",
                "Computer virus",
                "Jews",
                "Jake Gyllenhaal",
                "2004 Indian Ocean earthquake and tsunami",
                "Dinosaur",
                "The Hangover",
                "Hillary Rodham Clinton",
                "Jimmy Carter",
                "The Sopranos",
                "Characters of Glee",
                "Michelangelo",
                "Will Ferrell",
                "Middle Ages",
                "Fidel Castro",
                "Austria",
                "PlayStation Portable",
                "Czech Republic",
                "Marie Antoinette",
                "Carbon dioxide",
                "Foo Fighters",
                "Stone Cold Steve Austin",
                "Chronic obstructive pulmonary disease",
                "The Amazing Spider-Man (2012 film)",
                "Teenage Mutant Ninja Turtles",
                "Atheism",
                "Iron Maiden",
                "Domain Name System",
                "Woody Allen",
                "Berlin Wall",
                "Google Maps",
                "Kareena Kapoor Khan",
                "Eddie Murphy",
                "Mel Gibson",
                "Black hole",
                "Watchmen (film)",
                "Central processing unit",
                "Super Bowl",
                "Jupiter",
                "Slash (musician)",
                "Hulk (comics)",
                "List of Walt Disney Pictures films",
                "George Harrison",
                "Dominican Republic",
                "The Chronicles of Narnia",
                "John Travolta",
                "Hinduism",
                "Quinoa",
                "List of Dexter episodes",
                "Charlize Theron",
                "CM Punk",
                "M16 rifle",
                "Marketing",
                "Dwight D. Eisenhower",
                "Jacqueline Kennedy Onassis",
                "Halo (series)",
                "Intelligence quotient",
                "Meningitis",
                "Mathematics",
                "Hugh Hefner",
                "Attention deficit hyperactivity disorder",
                "LOL",
                "Chile",
                "Radiohead",
                "Order of the British Empire",
                "Enrique Iglesias",
                "Tom Brady",
                "Large Hadron Collider",
                "Penis enlargement",
                "List of tallest buildings and structures in the world",
                "Adam Levine",
                "United States Army",
                "Top Gear (2002 TV series)",
                "Ben Affleck",
                "Stephen King",
                "Amino acid",
                "The Elder Scrolls V: Skyrim",
                "Gerard Butler",
                "Harrison Ford",
                "Ronaldo",
                "Anderson Silva",
                "Keeping Up with the Kardashians",
                "Power Rangers",
                "Fedor Emelianenko",
                "Denzel Washington",
                "Roman numerals",
                "Down syndrome",
                "Newton's laws of motion",
                "John Mayer",
                "Toronto",
                "Cyprus",
                "The Matrix",
                "Kristen Bell",
                "Libya",
                "Bukkake",
                "Portugal",
                "Democracy",
                "Kim Jong-il",
                "Evolution",
                "First Amendment to the United States Constitution",
                "Julia Roberts",
                "Alprazolam",
                "Millennials",
                "Kane (wrestler)",
                "Horse",
                "Backstreet Boys",
                "Randy Orton",
                "Anne Boleyn",
                "Windows 8",
                "Non-penetrative sex",
                "Antarctica",
                "Ludacris",
                "Ultimate Fighting Championship",
                "Jeffrey Dahmer",
                "Borderline personality disorder",
                "Robin Williams",
                "Californication (TV series)",
                "Toy Story 3",
                "Ronaldinho",
                "Cunnilingus",
                "Amanda Seyfried",
                "Fibonacci number",
                "United States dollar",
                "Croatia",
                "Anemia",
                "Apartheid",
                "Mother Teresa",
                "Bane (comics)",
                "Breaking Dawn",
                "Dancing with the Stars (U.S. TV series)",
                "Mao Zedong",
                "Acoustic-electric guitar",
                "M.I.A. (rapper)",
                "Sex and the City",
                "Cher",
                "U.S. state",
                "Syria",
                "Glock",
                "Georgia (country)",
                "Walmart",
                "Cleopatra",
                "Nineteen Eighty-Four",
                "Heroin",
                "Malware",
                "Skype",
                "Tim Burton",
                "List of sovereign states",
                "Film",
                "Bugatti Veyron",
                "Las Vegas",
                "The Pirate Bay",
                "Lyme disease",
                "Zoophilia"};
    }
}
